export default {
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILED:'LOGIN_FAILED',
    RECEIVE_USER:'RECEIVE_USER',
    ERROR_MESSAGE:'ERROR_MESSAGE',
    LOG_OUT:'LOG_OUT',

    SEND_MESSAGE:'SEND_MESSAGE',//向服务端发送消息
    RECEIVE_MSG_LIST:'RECEIVE_MSG_LIST',//接收服务器发送的所有相关消息
    RECEIVE_MSG:'RECEIVE_MSG',//接收服务器发送的单条消息
    MSG_READ:'MSG_READ'//将消息标记为已读
}
