export default {
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILED:'LOGIN_FAILED',
    RECEIVE_USER:'RECEIVE_USER',
    ERROR_MESSAGE:'ERROR_MESSAGE',
    LOG_OUT:'LOG_OUT',

    SEND_MESSAGE:'SEND_MESSAGE',
    RECEIVE_MSG_LIST:'RECEIVE_MSG_LIST',
    RECEIVE_MSG:'RECEIVE_MSG',
    MSG_READ:'MSG_READ'
}
